apiVersion: v1
kind: PersistentVolume
metadata: 
   name: wordpress-persistent-storage
spec:
  capacity:
    storage: 1 Gi
  volumeMode: Filesystem
  accessMode: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions: 
     - hard
     - nfsvers=4.1
  nfs:
    path: /html